### ISSUE TITLE
 Exception com.androidnetworking.error.ANError: Samsung S8 & S8+

### ISSUE THREAD

**Issue by elmalote** [amitshekhariitbhu/Fast-Android-Networking#134]
I am getting an exception when calling a simple GET or PUT using Samsung devices. 
My Firebase crash report is showing the following exception:

**com.androidnetworking.internal.InternalRunnable.executeSimpleRequest (InternalRunnable.java:80)
com.androidnetworking.internal.InternalRunnable.run (InternalRunnable.java:54)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:428)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
com.androidnetworking.core.PriorityThreadFactory$1.run (PriorityThreadFactory.java:47)
java.lang.Thread.run (Thread.java:762)**

The request is called over SSL signed CA certificate which the phones accept.
Structrure of the GET request is:
https://myurl.com:port/pathParam/pathParam/pathParam/pathParam/pathParam?queryParam

I am also adding two headers. API key and application/json content type.

Unfortunately I don't have the device under debugging and only have the crash report from Firebase.

Gradle build:
**'com.amitshekhar.android:android-networking:1.0.0'**

I have tested my app against the emulator, Huawei Mate 9 Pro, Huawei Honor 6, Xiaomi Mi5 and LG Optimus G.
Ranging from Android version 4.4 to 7.0, no issues.

**Comment by amitshekhariitbhu** [comment]
@elmalote Let me check it once.

**Comment by elmalote** [comment]
The error was on my end.
Sorry :(

**Comment by dco5** [comment]
@elmalote What was the error? I am also getting the same error

**Comment by hunt979** [comment]
i am also getting the same error.What is the solution @elmalote @amitshekhariitbhu 

com.androidnetworking.error.ANError
                  at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:83)
                  at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:56)
                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                  at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
                  at java.lang.Thread.run(Thread.java:818)

**Comment by hasnain-ahmad** [comment]
@elmalote Please share your experience/solution in the post.
