### ISSUE TITLE
PUT request with List<Integer>

### ISSUE THREAD

**Issue by AndrewParkhomov** [amitshekhariitbhu/Fast-Android-Networking#184]
Hi, I'm trying to make put request

```
@Override
public Observable<UpdateDriverDataResponse>
 updateUserData(WrapperClass.UpdateDriverData updateData) {
        return Rx2AndroidNetworking.put(ApiEndPoint.ENDPOINT_UPDATE_DRIVER_DATA)
                .addHeaders(mApiHeader.getTokenApiHeader())
                .addBodyParameter(updateData)
                .setOkHttpClient(Utils.getOkHttpClient())
                .build()
                .getObjectObservable(UpdateDriverDataResponse.class);
    }
```

My "updateData" object contain List<Integer>. (If updateData contain String or Integer objects it's working perfectly, bug? only when I'm try to put List) 
In logcat I have an error  
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 10 path $.
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.androidnetworking.gsonparserfactory.GsonParserFactory.getStringMap(GsonParserFactory.java:85)
	at com.androidnetworking.common.ANRequest$PostRequestBuilder.addBodyParameter(ANRequest.java:1263)
        at com.wozward.tonadriver.network.AppApiHelper.updateUserData(AppApiHelper.java:384)
        at com.wozward.tonadriver.tabs.profile.profile.truck.main.TruckPresenter.updateUserData(TruckPresenter.java:111)
        at com.wozward.tonadriver.tabs.profile.profile.truck.main.Truck.onUpdateDriverDataClicked(Truck.java:241)
        at com.wozward.tonadriver.tabs.profile.profile.truck.main.Truck_ViewBinding$1.doClick(Truck_ViewBinding.java:74)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
 Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 10 path $.
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:887)
`
I'm trying to put it in HashMap, but still have same error

```
HashMap<String, List<Integer>> test= new HashMap<String,  List<Integer>>();
        List<Integer> load = new ArrayList<>();
        load.add(33);
        test.put("load", load);

```
Question: What I do wrong? 
Thank you!

**Comment by AndrewParkhomov** [comment]
I'm figured out

**Comment by FarisJakpau** [comment]
Hi, can you share your answer?
