### ISSUE TITLE
com.androidnetworking.error.ANError: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by vinjex** [amitshekhariitbhu/Fast-Android-Networking#219]
I've been using this library for months now but I'm unable to get a response for this request:
```
AndroidNetworking.post(myURL)
  .addHeaders("Content-Type", "application/json")
  .addHeaders("Authorization", myTOKEN)
  .addHeaders("Accept", "application/json")
  .addBodyParameter("param1", a)
  .addBodyParameter("param2", b)
  .addBodyParameter("param3", c)
  .addBodyParameter("param4", d)
  .addBodyParameter("param5", e)
  .setPriority(Priority.MEDIUM)
  .build()
  .getAsJSONObject(new JSONObjectRequestListener() {
      @Override
      public void onResponse(JSONObject response) {
        Log.d(TAG, "onResponse: " + response);
        DO STUFF
      }

      @Override
      public void onError(ANError anError) {
        hideDialog();
        firebaseAuth.signOut();
        Log.e(TAG, "onError: ", anError.fillInStackTrace());
        Log.d(TAG, "onError response " + anError.getResponse());
      }
});
```

All the params are != null and the same request with the same params works during tests made with Postman. The errors are two:
* The first appears as a system error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
     at okhttp3.HttpUrl.canonicalize(HttpUrl.java:1868)
     at okhttp3.FormBody$Builder.add(FormBody.java:110)
     at com.androidnetworking.common.ANRequest.getRequestBody(ANRequest.java:818)
     at com.androidnetworking.internal.InternalNetworking.performSimpleRequest(InternalNetworking.java:76)
     at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:68)
     at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
     at java.lang.Thread.run(Thread.java:761)
```
* The second comes from my log.e (_Log.e(TAG, "onError: ", anError.fillInStackTrace());_):
```
com.androidnetworking.error.ANError: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
   at com.my.application.LoginActivity$9$1.onError(LoginActivity.java:393)
   at com.androidnetworking.common.ANRequest.deliverErrorResponse(ANRequest.java:729)
   at com.androidnetworking.common.ANRequest.deliverError(ANRequest.java:663)
   at com.androidnetworking.internal.InternalRunnable$1.run(InternalRunnable.java:159)
   at android.os.Handler.handleCallback(Handler.java:751)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:241)
   at android.app.ActivityThread.main(ActivityThread.java:6274)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
   at java.util.ArrayList.get(ArrayList.java:411)
   at java.util.Collections$UnmodifiableList.get(Collections.java:1295)
   at okhttp3.FormBody.writeOrCountBytes(FormBody.java:93)
   at okhttp3.FormBody.contentLength(FormBody.java:66)
   at com.androidnetworking.interceptors.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:167)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
   at okhttp3.RealCall.execute(RealCall.java:63)
   at com.androidnetworking.internal.InternalNetworking.performSimpleRequest(InternalNetworking.java:112)
   at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:68)
   at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
   at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
   at java.lang.Thread.run(Thread.java:761)
```

Any help would be appreciated.

**Comment by amitshekhariitbhu** [comment]
Can you please check the values that you are passing that will help me in debugging the issue.

**Comment by vinjex** [comment]
All the values are Strings. To check if the error was from the way the values are retrieved I tried using hardcoded strings but to no avail.

**Comment by torrin-swanson** [comment]
Incase you're stuck. Making sure my values we're not null resolved the issue for me.

**Comment by rohit6027** [comment]
Map<String, String> params = new HashMap<>();
        params.put("first_name", fnameStr);
        params.put("last_name", lnameStr);
        params.put("client_id", prefManager.getPreference(AppConstant.VCiTa_ID,""));
        params.put("interaction_type", "online");
        params.put("start_time", "2018-05-10");
       params.put("duration", AppConstant.Service_Duration);
       /* params.put("title", AppConstant.Service_Name);
        params.put("interaction_details","dfsdfsd");*/

        ProgressDialogUtils.showDialog(getActivity());
        if(NetworkUtils.isOnline(Objects.requireNonNull(getActivity())))
        {
            AndroidNetworking.post(URL.SubMITFOrm)
                    .addBodyParameter(params) 
--------------------------------
}
}


I am also getting IndexOutOfBound error

**Comment by ivanove** [comment]
I had the same issue, after debbuging I found that one param was null, so try to check every parameters, good luck
