### ISSUE TITLE
how to mock FAN 

### ISSUE THREAD

**Issue by IamFive** [amitshekhariitbhu/Fast-Android-Networking#233]
I try to make some unittests with FAN API calls, but exceptions below was thrown.
And it seems it's not easy to mock the `com.androidnetworking.core.Core`, it initialize mExecutorSupplier in constructor directly, and could only access by static method.

```
java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.os.Looper.getMainLooper(Looper.java)
	at com.androidnetworking.core.MainThreadExecutor.<init>(MainThreadExecutor.java:30)
	at com.androidnetworking.core.DefaultExecutorSupplier.<init>(DefaultExecutorSupplier.java:39)
	at com.androidnetworking.core.Core.<init>(Core.java:29)
	at com.androidnetworking.core.Core.getInstance(Core.java:36)
	at com.androidnetworking.internal.ANRequestQueue.addRequest(ANRequestQueue.java:125)
	at com.androidnetworking.common.ANRequest.getAsJSONObject(ANRequest.java:227)
	at manager.server.huawei.com.servermanager.redfish.RedfishClient.getSystems(RedfishClient.java:206)
	at manager.server.huawei.com.servermanager.RedfishClientUnitTest$1.run(RedfishClientUnitTest.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by IamFive** [comment]
any example code will be great

**Comment by amitshekhariitbhu** [comment]
If you are using rx version of the library. check [this](https://github.com/MindorksOpenSource/android-mvp-architecture/blob/master/app/src/test/java/com/mindorks/framework/mvp/ui/login/LoginPresenterTest.java)

**Comment by amitshekhariitbhu** [comment]
Also refer [this](https://github.com/amitshekhariitbhu/Fast-Android-Networking/blob/master/android-networking/src/androidTest/java/com/androidnetworking/GetJSONApiTest.java)

**Comment by IamFive** [comment]
thanks for the help.

I hope we could test the FAN API Client out of the Android Application scope.
