### ISSUE TITLE
LinkedTreeMap cannot be cast to ... Generic Class

### ISSUE THREAD

**Issue by adisiji** [amitshekhariitbhu/Fast-Android-Networking#250]
I have below code to deserialize the json response from ApiBaseResponse and it worked fine. But I wanted to make the code to be generic, so I make extension function in Kotlin. 
Could you please help me how I can fix this error? 
Thanks in advance.

It worked :
```
Rx2AndroidNetworking.get(ENDPOINT_PROMO)
        .build()
        .getParseObservable(object : TypeToken<ApiBaseResponse<List<BannerPromo>>>(){})
        .map {
          it.dataApi
        }
```

It doesn't :
```
inline fun <reified T> Rx2ANRequest.getData() = 
      getParseObservable(object : TypeToken<ApiBaseResponse<T>>(){}).map { 
    it.dataApi
  }
```

Error Log: 
```
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.dritama.wowpremi.data.models.api.BannerPromo
                                                                                          at com.dritama.wowpremi.ui.home.HomeViewModel$getListPromo$1.accept(HomeViewModel.kt:99)
                                                                                          at com.dritama.wowpremi.ui.home.HomeViewModel$getListPromo$1.accept(HomeViewModel.kt:16)
                                                                                          at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
                                                                                          at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                                                          at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                                          at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                          at android.os.Handler.handleCallback(Handler.java:789)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by lam-bun** [comment]
I have the same issue.
