### ISSUE TITLE
response.body() is no close?

### ISSUE THREAD

**Issue by chengzijian** [amitshekhariitbhu/Fast-Android-Networking#259]
E/StrictMode( 2567): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
E/StrictMode( 2567): java.lang.Throwable: Explicit termination method 'response.body().close()' not called
E/StrictMode( 2567): 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
E/StrictMode( 2567): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/StrictMode( 2567): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/StrictMode( 2567): 	at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:340)
E/StrictMode( 2567): 	at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:155)
E/StrictMode( 2567): 	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
E/StrictMode( 2567): 	at okhttp3.RealCall.execute(RealCall.java:73)
E/StrictMode( 2567): 	at com.androidnetworking.internal.InternalNetworking.performSimpleRequest(InternalNetworking.java:117)
E/StrictMode( 2567): 	at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:70)
E/StrictMode( 2567): 	at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:55)
E/StrictMode( 2567): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/StrictMode( 2567): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/StrictMode( 2567): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/StrictMode( 2567): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/StrictMode( 2567): 	at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
E/StrictMode( 2567): 	at java.lang.Thread.run(Thread.java:841)

**Comment by chengzijian** [comment]
I think I probably know what's going on. I'm using the xiaomi android6.0 system, and it's normal to turn off the smart power-saving feature. and thank for your reply.
