### ISSUE TITLE
Random errors 

### ISSUE THREAD

**Issue by sandeep7644** [amitshekhariitbhu/Fast-Android-Networking#276]
i am getting random errors while calling my webservices using Android fast networking library

Error:com.androidnetworking.error.ANError at com.androidnetworking.common.ANRequest.cancel(SourceFile:560) at com.androidnetworking.internal.ANRequestQueue.cancel(SourceFile:64) at com.androidnetworking.internal.ANRequestQueue.cancelRequestWithGivenTag(SourceFile:96) at com.androidnetworking.AndroidNetworking.cancel(SourceFile:223) at com.techwaveweb.concorderp.fragments.dashboard_fragments.Dashboard.onDestroy(SourceFile:272) at android.support.v4.app.Fragment.performDestroy(SourceFile:2434) at android.support.v4.app.FragmentManagerImpl.a(SourceFile:1442) at android.support.v4.app.FragmentManagerImpl.c(SourceFile:1528) at android.support.v4.app.FragmentManagerImpl.a(SourceFile:1595) at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(SourceFile:2951) at android.support.v4.app.FragmentController.dispatchDestroy(SourceFile:271) at android.support.v4.app.FragmentActivity.onDestroy(SourceFile:390) at android.support.v7.app.AppCompatActivity.onDestroy(SourceFile:209) at com.techwaveweb.concorderp.activities.CommonBaseActivity.onDestroy(SourceFile:77) at com.techwaveweb.concorderp.activities.NewDashboardActivity.onDestroy(SourceFile:379) at android.app.Activity.performDestroy(Activity.java:7086) at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154) at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4308) at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4339) at android.app.ActivityThread.-wrap6(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:163) at android.app.ActivityThread.main(ActivityThread.java:6379) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by amitshekhariitbhu** [comment]
Can you please provide more details? When are you facing this issue?

**Comment by zenkhas** [comment]
I'm facing same issue, I'm using my own class which is wrapper around Fast-Android-Networking and the cancel is inside destroy event based on LifecycleOwner.
