### ISSUE TITLE
Crashes when trying to get body from OkHttpResponse as response

### ISSUE THREAD

**Issue by Dr-Faust** [amitshekhariitbhu/Fast-Android-Networking#325]
Made everything as mentioned here: 
https://amitshekhar.me/Fast-Android-Networking/getting_okhttpresponse.html

But it crashes here:
Log.d(TAG, "response : " + response.body().source().readUtf8());

Here is my code:
`private void requestForSMS(final String phoneNumber)
    {
	    AndroidNetworking.post(Config.URL_REQUEST_SMS).addBodyParameter("phone_number", phoneNumber)
		    .setPriority(Priority.LOW)
		    .build()
		    .getAsOkHttpResponse(new OkHttpResponseListener() {
			    @Override
			    public void onResponse(Response response) {
				    if (response.isSuccessful()) {
					    Log.d(TAG, "Headers :" + response.headers());
					    String header =  response.headers().get("Set-Cookie");
					    if (header != null) {
						    cookie = header.substring(0, 44);
					    }
					    try {
						    Log.d(TAG, "Response : " + response.body().source().readUtf8());
						    String jsonBody = response.body().source().readUtf8();
						    JSONObject responseObj = new JSONObject(jsonBody);

						    String status = responseObj.getString("status");

						    // checking for error, if not error SMS is initiated
						    // device should receive it shortly
						    if (status.equals("success"))
						    {
							    mobile_num = responseObj.getString("phone_number");
							    // boolean flag saying device is waiting for sms
							    pref.setIsWaitingForSms(true);

							    // moving the screen to next pager item i.e otp screen
							    viewPager.setCurrentItem(1);
						    }
						    else
						    {
							    inputLayoutMobile.setError(getString(R.string.wrong_number));
							    Toast.makeText(getApplicationContext(), R.string.no_such_number, Toast.LENGTH_LONG).show();
						    }
						    // hiding the progress bar
						    progressBar.setVisibility(View.GONE);
					    } catch (JSONException | IOException e) {
						    e.printStackTrace();
					    }
				    }
			    }
			    @Override
			    public void onError(ANError error) {
				    Log.e(TAG, "ERROR MESSAGE: " + error.getMessage());
				    int errorCode = error.getErrorCode();
				    Log.e(TAG, "ERROR CODE: " + errorCode);
				    String errorMessage = "UNKNOWN ERROR";
				    if (errorCode == 0) {
					    errorMessage = "FAILED TO CONNECT SERVER";
				    }
				    else {
					    switch (errorCode) {
						    case 404:
							    errorMessage = "RESOURCE NOT FOUND";
							    break;
						    case 401:
							    errorMessage = "PLEASE LOG IN AGAIN";
							    break;
						    case 400:
							    errorMessage = "CHECK YOUR INPUTS";
							    break;
						    case 500:
							    errorMessage = "SOMETHING IS GETTING WRONG";
							    break;
					    }
				    }
				    Log.e(TAG, "ERROR: " + errorMessage);
				    Log.d(TAG, "onError errorCode : " + error.getErrorCode());
				    Log.d(TAG, "onError errorBody : " + error.getErrorBody());
				    Log.d(TAG, "onError errorDetail : " + error.getErrorDetail());
				    error.printStackTrace();
			    }
		    });
    }
`
Here is stack trace: 
07-24 13:56:48.125 32203-32203/com.gaztron.gtlogistics D/LoginActivity: Headers :Content-Type: text/html; charset=utf-8
    Content-Length: 49
    Set-Cookie: session=5daffb48-a43d-468a-beae-e6f962704e7f; Expires=Fri, 24-Aug-2018 10:56:48 GMT; HttpOnly; Path=/
    Date: Tue, 24 Jul 2018 10:56:48 GMT
07-24 13:56:48.135 32203-32203/com.gaztron.gtlogistics D/AndroidRuntime: Shutting down VM
07-24 13:56:48.145 32203-32203/com.gaztron.gtlogistics E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gaztron.gtlogistics, PID: 32203
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:249)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
        at okio.Buffer.writeAll(Buffer.java:1053)
        at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:188)
        at com.myproject.LoginActivity$2.onResponse(LoginActivity.java:304)
        at com.androidnetworking.common.ANRequest$8.run(ANRequest.java:796)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6117)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Maybe I'm doing something wrong?

**Comment by xikitidistant** [comment]
android.os.NetworkOnMainThreadException -> In Android, your network calls always needs to be executed **OUT** of the MainThread.

You can use AsynckTask or a Service to do that:
AsynckTask:
https://stackoverflow.com/questions/6343166/how-do-i-fix-android-os-networkonmainthreadexception

Services:
https://developer.android.com/training/run-background-service/create-service
