### ISSUE TITLE
Crashes when uploading multipart. 

### ISSUE THREAD

**Issue by beingentangled** [amitshekhariitbhu/Fast-Android-Networking#354]
> Please throw some light on this log

 E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean okhttp3.Call.isCanceled()' on a null object reference
        at com.rx2androidnetworking.Rx2InternalNetworking$MultipartANObservable.subscribeActual(Rx2InternalNetworking.java:414)
        at io.reactivex.Observable.subscribe(Observable.java:10981)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:2801)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Rohitsachdeva** [comment]
pls add some comments, why it is closed

**Comment by amitshekhariitbhu** [comment]
@beingentangled Can you please tell if you have solved?

**Comment by DibSarkar** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean okhttp3.Call.isCanceled()' on a null object reference
