### ISSUE TITLE
com.androidnetworking.error.ANError

### ISSUE THREAD

**Issue by hasnain-ahmad** [amitshekhariitbhu/Fast-Android-Networking#361]
Hi @amitshekhariitbhu 
We are getting this error. How can we resolve it?
```
at com.rx2androidnetworking.Rx2InternalNetworking$SimpleANObservable.subscribeActual(Rx2InternalNetworking.java:214)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```
Is there is any way to check the server is working fine and its response time is good?
How to handle the following DB deadlock

> Transaction (Process ID 105) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

**Comment by hasnain-ahmad** [comment]
> @hasnain-ahmad Can you provide the code snippet?

https://pastebin.com/sBkzenQZ
https://pastebin.com/0jBS0XCv

**Comment by hasnain-ahmad** [comment]
> > @hasnain-ahmad Can you provide the code snippet?
> 
> https://pastebin.com/sBkzenQZ
> https://pastebin.com/0jBS0XCv
Did you need this snippet or also need something else.

**Comment by arslan555** [comment]
I also got this error, not on every device but on some devices. @amitshekhariitbhu, please tell the solution if you have resolved it.

**Comment by amitshekhariitbhu** [comment]
@arslan555 @hasnain-ahmad Have you solved this? Let me know I will check it.

**Comment by longdcnb1998** [comment]
> @arslan555 @hasnain-ahmad Have you solved this? Let me know I will check it.

i got the same error on device samsung J7, android 8.1.0

**Comment by jfaq89** [comment]
Any news here?
