### ISSUE TITLE
Error Proguard Release com.fasterxml.jackson.databind

### ISSUE THREAD

**Issue by YovanggaAnandhika** [amitshekhariitbhu/Fast-Android-Networking#363]
i get a if release apk build project. java compiler.
how i solve this ?

`Caused by java.lang.NoSuchFieldException: No field PUBLIC_ONLY in class Lcom/c/a/a/e$a; (declaration of 'com.c.a.a.e$a' appears in /data/app/product.multitekhnologi.menangkandidat-2/base.apk)
       at java.lang.Class.getDeclaredField(Class.java)
       at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:685)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
       at java.lang.Class.getAnnotation(Class.java:359)
       **at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.(Unknown Source)
       at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.defaultInstance(Unknown Source)
       at com.fasterxml.jackson.databind.ObjectMapper.(Unknown Source)
       at com.jacksonandroidnetworking.JacksonParserFactory.(Unknown Source)**
       at product.multitekhnologi.menangkandidat.Modules.EngineBase.ApplicationController.onCreate(Unknown Source)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4761)
       at android.app.ActivityThread.access$1700(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:5523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

**Comment by YovanggaAnandhika** [comment]
No Response
