### ISSUE TITLE
error on multipart upload 

### ISSUE THREAD

**Issue by namkazt** [amitshekhariitbhu/Fast-Android-Networking#413]
note: no logging enable 

code block: 
` ANRequest.MultiPartBuilder builder = withToken(upload(url("create-profile")))
                .setPriority(Priority.HIGH)
                .addMultipartParameter("username", userName)
                .addMultipartParameter("email", email)
        if (avatar != null){
            builder.addMultipartFile("avatar", avatar);
        }
        return builder.build();`
` request.getAsJSONObject(new JSONObjectRequestListener() {
            @Override
            public void onResponse(JSONObject response) {
               .....
            }
            @Override
            public void onError(ANError anError) {
                // ---------> error print here
                Crashlytics.logException(anError);
                anError.printStackTrace();
                if(callback != null)
                    callback.onComplete(PRESENTER_REQUEST_INTERNAL_ERROR, "", null);
                dialogError("[Internal Error] Please contact developer.");
            }
        });`

here is stack trace:
`W/System.err: com.androidnetworking.error.ANError: java.lang.IllegalStateException: closed
        at com.androidnetworking.internal.InternalRunnable.executeUploadRequest(InternalRunnable.java:148)
W/System.err:     at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:61)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
W/System.err: Caused by: java.lang.IllegalStateException: closed
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:40)
W/System.err:     at okio.ForwardingSink.write(ForwardingSink.java:35)
        at com.androidnetworking.internal.RequestProgressBody$1.write(RequestProgressBody.java:74)
W/System.err:     at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
W/System.err:     at com.androidnetworking.internal.RequestProgressBody.writeTo(RequestProgressBody.java:64)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
        at com.androidnetworking.internal.InternalNetworking.performUploadRequest(InternalNetworking.java:244)
W/System.err:     at com.androidnetworking.internal.InternalRunnable.executeUploadRequest(InternalRunnable.java:123)`

**Comment by namkazt** [comment]
look like issue in `com.androidnetworking.internal.RequestProgressBody`

`@Override
    public void writeTo(BufferedSink sink) throws IOException {
        if (bufferedSink == null) {
            bufferedSink = Okio.buffer(sink(sink));
        }
        requestBody.writeTo(bufferedSink);
        // at interceptors.add(new CallServerInterceptor(forWebSocket)); sink is closed
        bufferedSink.flush();
    }`

**Comment by namkazt** [comment]
edit that method to :
```@Override
    public void writeTo(BufferedSink sink) throws IOException {
        bufferedSink = Okio.buffer(sink(sink));
        requestBody.writeTo(bufferedSink);
        bufferedSink.flush();
    }```
fix the problem
