### ISSUE TITLE
com.androidnetworking.error.ANError

### ISSUE THREAD

**Issue by codejunk1e** [amitshekhariitbhu/Fast-Android-Networking#537]
Getting this error when I try to register a user with this networking library, based on what I have been seeing, it fails because of a bad request
```
2020-10-08 15:41:31.716 31042-31042/com.footballmania.com W/System.err: com.androidnetworking.error.ANError
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at com.rx2androidnetworking.Rx2InternalNetworking$SimpleANObservable.subscribeActual(Rx2InternalNetworking.java:214)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2020-10-08 15:41:31.717 31042-31042/com.footballmania.com W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-10-08 15:41:31.718 31042-31042/com.footballmania.com W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-10-08 15:41:31.718 31042-31042/com.footballmania.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-10-08 15:41:31.718 31042-31042/com.footballmania.com W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-10-08 15:41:31.718 31042-31042/com.footballmania.com W/System.err:     at java.lang.Thread.run(Thread.java:764)

```

This is the method code for the registration,  I haven't seen any bad requests on it.

```
    public void register(String username, String email, String password, String userRefId) {

        setIsLoading(true);
        getCompositeDisposable().add(getDataManager()
                .doServerRegisterApiCall(new RegisterRequest.ServerRegisterRequest(username, email, password, userRefId))
                .doOnSuccess(response -> getDataManager()
                        .updateUserInfo(
                                response.getJwt(),
                                response.getUser().getId(),
                                userRefId,
                                DataManager.LoggedInMode.LOGGED_IN_MODE_SERVER,
                                response.getUser().getUsername(),
                                response.getUser().getEmail(),
                                response.getUser().getPhotoUrl()))
                .subscribeOn(getSchedulerProvider().io())
                .observeOn(getSchedulerProvider().ui())
                .subscribe(response -> {
                    setIsLoading(false);
                    getNavigator().openMainActivity();
                }, throwable -> {
                    setIsLoading(false);
                    ErrorResponse errorResponse = getError(throwable);
                    throwable.printStackTrace();
                    getNavigator().handleError(errorResponse);
                }));

    }
```

**Comment by amitshekhariitbhu** [comment]
Are you getting the onError callback?

**Comment by codejunk1e** [comment]
So sorry for leaving this open for a long time! I have fixed this error, I was making a "bad request" to the server. Thanks for the awesome library @amitshekhariitbhu
