### ISSUE TITLE
java.lang.IllegalStateException: Expected Android API level 21+ but was 30

### ISSUE THREAD

**Issue by winnerawan** [amitshekhariitbhu/Fast-Android-Networking#545]
```
java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
        at com.androidnetworking.internal.InternalNetworking.getDefaultClient(InternalNetworking.java:289)
        at com.androidnetworking.internal.InternalNetworking.getClient(InternalNetworking.java:267)
        at com.androidnetworking.internal.InternalNetworking.<clinit>(InternalNetworking.java:60)
        at com.androidnetworking.internal.InternalNetworking.setClientWithCache(InternalNetworking.java:297)
        at com.androidnetworking.AndroidNetworking.initialize(AndroidNetworking.java:63)
        at xx.xxxx.xxx.onCreate(App.java:47)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7433)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7374)
        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.internal.platform.Platform.get(Platform.java:85) 
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202) 
        at com.androidnetworking.internal.InternalNetworking.getDefaultClient(InternalNetworking.java:289) 
        at com.androidnetworking.internal.InternalNetworking.getClient(InternalNetworking.java:267) 
        at com.androidnetworking.internal.InternalNetworking.<clinit>(InternalNetworking.java:60) 
        at com.androidnetworking.internal.InternalNetworking.setClientWithCache(InternalNetworking.java:297) 
        at com.androidnetworking.AndroidNetworking.initialize(AndroidNetworking.java:63) 
        at xx.xxxx.xxx.onCreate(App.java:47) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7433) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7374) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:301) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

**Comment by winnerawan** [comment]
solution, add
```
implementation("com.squareup.okhttp3:okhttp:4.9.0")
```
