### ISSUE TITLE
Unable to load data through this library in Android 11

### ISSUE THREAD

**Issue by Mahabub21** [amitshekhariitbhu/Fast-Android-Networking#546]
In android 11, I am unable to load data why? Here is the problem I found but unable to solve it. Please, update your project we are depending on this.

I/Timeline: Timeline: Activity_launch_request time:323450230
V/FA: Recording user engagement, ms: 23751
V/FA: Connecting to remote service
V/FA: Activity paused, time: 451578314
V/FA: onActivityCreated
V/FA: Connection attempt already in progress
I/com.ufl.moapp4: Rejecting re-init on previously-failed class java.lang.Class<com.androidnetworking.internal.InternalNetworking>: java.lang.ExceptionInInitializerError: 
        at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform.get() (Platform.java:85)
        at javax.net.ssl.SSLSocketFactory okhttp3.OkHttpClient.newSslSocketFactory(javax.net.ssl.X509TrustManager) (OkHttpClient.java:296)
        at void okhttp3.OkHttpClient.<init>(okhttp3.OkHttpClient$Builder) (OkHttpClient.java:262)
        at void okhttp3.OkHttpClient.<init>() (OkHttpClient.java:235)
        at okhttp3.OkHttpClient com.androidnetworking.internal.InternalNetworking.getDefaultClient() (InternalNetworking.java:289)
        at okhttp3.OkHttpClient com.androidnetworking.internal.InternalNetworking.getClient() (InternalNetworking.java:267)
        at void com.androidnetworking.internal.InternalNetworking.<clinit>() (InternalNetworking.java:60)
        at okhttp3.Response com.androidnetworking.internal.InternalNetworking.performSimpleRequest(com.androidnetworking.common.ANRequest) (InternalNetworking.java:-1)
        at void com.androidnetworking.internal.InternalRunnable.executeSimpleRequest() (InternalRunnable.java:70)
        at void com.androidnetworking.internal.InternalRunnable.run() (InternalRunnable.java:55)
        at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:462)
        at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
        at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
        at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
        at void com.androidnetworking.core.PriorityThreadFactory$1.run() (PriorityThreadFactory.java:47)
        at void java.lang.Thread.run() (Thread.java:923)
V/FA: Activity resumed, time: 451578381
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
D/OpenGLRenderer: endAllActiveAnimators on 0xb40000796b250800 (NavigationMenuItemView) with handle 0xb4000079da95cac0
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 4
V/FA: Inactivity, disconnecting from the service
W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: ls@c1ca21d
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1765)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1884)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:803)
        at ci.f(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):1)
        at ci.d(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):2)
        at lt.E(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):9)
        at ld.a(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):3)
        at ef.run(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iy.run(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):5)
V/FA: Recording user engagement, ms: 15732
V/FA: Connecting to remote service
V/FA: Activity paused, time: 451594114
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2
D/FA: Application going to the background
W/System: A resource failed to call release. 
V/FA: Inactivity, disconnecting from the service
W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: ls@c1ca21d
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1765)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1884)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:803)
        at ci.f(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):1)
        at ci.d(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):2)
        at lt.E(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):9)
        at ld.a(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):3)
        at ef.run(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iy.run(:com.google.android.gms.dynamite_measurementdynamite@205016097@20.50.16 (150400-0):5)

**Comment by Kdot94** [comment]
Hello @Mahabub21 same issue here. Any ideia on how to solve it?

**Comment by Mahabub21** [comment]
> Hello @Mahabub21 same issue here. Any ideia on how to solve it?

Not Yet. This library is not updated. Now, I am using Loader Manager and remove this library.
