### ISSUE TITLE
Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/androidnetworking/internal/InternalNetworking;

### ISSUE THREAD

**Issue by Aviswanathan** [amitshekhariitbhu/Fast-Android-Networking#74]
**Hi,**

**Am getting this error while making POST request to server.**

**Emulator Android Version: 4.4**

VFY: unable to find class referenced in signature (Lokhttp3/internal/io/RealConnection;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/io/RealConnection;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/http/StreamAllocation;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/http/StreamAllocation;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/io/RealConnection;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/io/RealConnection;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/io/RealConnection;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/internal/io/RealConnection;)
W/dalvikvm: VFY: unable to resolve static field 35368 (INSTANCE) in Lokhttp3/internal/tls/OkHostnameVerifier;
D/dalvikvm: VFY: replacing opcode 0x62 at 0x0037
W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/androidnetworking/internal/InternalNetworking;

**Comment by amitshekhariitbhu** [comment]
@Aviswanathan  which version you are using and can you share the code or give me more detail?

**Comment by Aviswanathan** [comment]
Yes.. am using Android version as 4.4.2 ..
I tried to initialize the Android Networking in Application Class.At the time am getting this error:

java.lang.NoClassDefFoundError: okhttp3.internal.tls.OkHostnameVerifier
                                                                         at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:364)
                                                                         at okhttp3.OkHttpClient.<init>(OkHttpClient.java:151)
                                                                         at com.androidnetworking.internal.InternalNetworking.getDefaultClient(InternalNetworking.java:310)
                                                                         at com.androidnetworking.internal.InternalNetworking.getClient(InternalNetworking.java:304)
                                                                         at com.androidnetworking.internal.InternalNetworking.<clinit>(InternalNetworking.java:55)
                                                                         at com.androidnetworking.AndroidNetworking.initialize(AndroidNetworking.java:59)

Please note that this error will not occured on API 22 and later.

And this dependencies are am using in my app gradle with mulitdexenabled


    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.amitshekhar.android:android-networking:0.1.0'
    compile 'com.android.support:design:24.1.1'
    compile 'com.android.support:cardview-v7:24.1.1'
    compile 'com.android.support:support-v4:24.1.1'
    compile 'com.google.android.gms:play-services:8.1.0'

    androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.0') {
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude module: 'recyclerview-v7'
    }

    androidTestCompile 'com.android.support:support-annotations:24.1.1'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    compile 'com.android.support.test.espresso:espresso-idling-resource:2.2.2'

**Comment by amitshekhariitbhu** [comment]
have you tried `compile 'com.amitshekhar.android:android-networking:0.3.0'` ?

**Comment by amitshekhariitbhu** [comment]
As far I understand the issue is coming because of Multidex. I will check it and find a way to handle it.

**Comment by Aviswanathan** [comment]
yes. i tried with 0.3.0.but got same error

**Comment by amitshekhariitbhu** [comment]
Please refer this 
http://blog.osom.info/2014/10/generating-main-dex-list-file.html

Meanwhile I am also checking.

**Comment by Aviswanathan** [comment]
Problem was fixed.

What i done is 

Instead of using **Application class** extends with **MultidexApplication class**,

then add this line    **MultiDex.install(base)**;

 in **attachBaseContext** override function

then add this dependency  in app gradle.
**compile 'com.android.support:multidex:1.0.1'**
